CODEFORCES_BASE_URL = 'https://codeforces.com/api'
PROBLEM_SET_URL = '/problemset.problems'
SUBMISSIONS_URL = '/user.status'

PPU_TEST_HANDLES = (
    'Enas410',
    'Craze.'
)

PPU_HANDLES = (
    'Craze.',
    'Sajedaswad',
    'tamimsall',
    'yasser_sharabati',
    '181002',
    'Momen-G-Ar',
    'GeekyCoder_PS',
    'zHeroFx',
    'kkk_Y',
    'onehb',
    'Omar_03',
    'Jinan_',
    'raghad__ns',
    'Areej_Shrouf',
    'Mohammad_Nayef',
    'Hatem25',
    'sondosamleh',
    'tarteel2003',
    'OmarAbuRish',
    'Safa.Kamal',
    'MoreAnyNot',
    'dala_bilal',
    'tissue_eater64',
    'shweiki',
    'Muhammad-herbawi',
    'IYAS.A.S',
    'Sarah-Abu-Irmeileh',
    'sara_adil',
    'NahlaTamimi',
    'saramanasra55',
    'A_Adnan',
    'SarahAlsharif',
    'easer',
    'AmjadKh',
    'basel_ebido',
    'Qasam_Himoony',
    'Semo_02',
    'QUAKKA',
    'sajaalmuraqtn',
    'Mariam_Hasanat',
    'meera_iyad',
    'NEBRASS',
    'h.h.h.h',
    'Basil_Aljamal',
    'Enas410',
    'HANEEN-BA',
    'Hazem_237',
    'abd_allah_sn',
)